# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/service/service.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "courier.ListUserPostsRequest" do
    optional :user_id, :int32, 1
  end
  add_message "courier.GetPostRequest" do
    optional :id, :int64, 1
  end
  add_message "courier.ImportPostRequest" do
    optional :user_id, :int32, 1
    optional :post, :message, 2, "courier.Post"
  end
  add_message "courier.CancelTweetRequest" do
    optional :id, :int64, 1
  end
  add_message "courier.UpdateTweetRequest" do
    optional :id, :int64, 1
    optional :body, :string, 2
  end
  add_message "courier.PostList" do
    repeated :posts, :message, 1, "courier.Post"
  end
  add_message "courier.Post" do
    optional :id, :int64, 7
    optional :item_id, :string, 1
    optional :feed_id, :int32, 2
    optional :content_html, :string, 3
    optional :content_text, :string, 4
    optional :title, :string, 5
    optional :url, :string, 6
    repeated :tweets, :message, 9, "courier.PostTweet"
  end
  add_message "courier.PostTweet" do
    optional :id, :int64, 1
    optional :post_id, :int64, 2
    optional :body, :string, 3
    optional :status, :enum, 4, "courier.PostTweet.Status"
  end
  add_enum "courier.PostTweet.Status" do
    value :DRAFT, 0
    value :CANCELED, 1
    value :POSTED, 2
  end
end

module Courier
  ListUserPostsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.ListUserPostsRequest").msgclass
  GetPostRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.GetPostRequest").msgclass
  ImportPostRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.ImportPostRequest").msgclass
  CancelTweetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.CancelTweetRequest").msgclass
  UpdateTweetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.UpdateTweetRequest").msgclass
  PostList = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.PostList").msgclass
  Post = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.Post").msgclass
  PostTweet = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.PostTweet").msgclass
  PostTweet::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.PostTweet.Status").enummodule
end
