# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
require 'twirp'
require_relative 'service_pb.rb'

module Courier
  class PostsService < Twirp::Service
    package 'courier'
    service 'Posts'
    rpc :GetUserPosts, ListUserPostsRequest, PostList, :ruby_method => :get_user_posts
  end

  class PostsClient < Twirp::Client
    client_for PostsService
  end
end
