sudo: false
language: ruby
rvm:
- 2.5.1
cache: bundler
before_install:
- gem install bundler -v 1.16.1
before_script:
- psql -c 'create database courier_posts_test;' -U postgres
- DATABASE_URL="postgres:///courier_posts_test" bundle exec rake db:migrate
services:
- postgresql
addons:
  postgresql: '9.6'
